window.WC2026 = {
  "meta": {
    "title": "World Cup 2026",
    "subtitle": "Canada · Mexico · USA",
    "lastUpdated": "2026-06-15T19:30:00Z",
    "asOf": "2026-06-15",
    "source": "Wikipedia / FIFA",
    "finalVenue": "MetLife Stadium, New York / New Jersey",
    "finalDate": "2026-07-19"
  },
  "teams": {
    "MEX": { "name": "Mexico", "flag": "🇲🇽" },
    "KOR": { "name": "South Korea", "flag": "🇰🇷" },
    "RSA": { "name": "South Africa", "flag": "🇿🇦" },
    "CZE": { "name": "Czechia", "flag": "🇨🇿" },
    "CAN": { "name": "Canada", "flag": "🇨🇦" },
    "SUI": { "name": "Switzerland", "flag": "🇨🇭" },
    "QAT": { "name": "Qatar", "flag": "🇶🇦" },
    "BIH": { "name": "Bosnia & Herz.", "flag": "🇧🇦" },
    "BRA": { "name": "Brazil", "flag": "🇧🇷" },
    "MAR": { "name": "Morocco", "flag": "🇲🇦" },
    "SCO": { "name": "Scotland", "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
    "HAI": { "name": "Haiti", "flag": "🇭🇹" },
    "USA": { "name": "United States", "flag": "🇺🇸" },
    "PAR": { "name": "Paraguay", "flag": "🇵🇾" },
    "AUS": { "name": "Australia", "flag": "🇦🇺" },
    "TUR": { "name": "Türkiye", "flag": "🇹🇷" },
    "GER": { "name": "Germany", "flag": "🇩🇪" },
    "ECU": { "name": "Ecuador", "flag": "🇪🇨" },
    "CIV": { "name": "Ivory Coast", "flag": "🇨🇮" },
    "CUW": { "name": "Curaçao", "flag": "🇨🇼" },
    "NED": { "name": "Netherlands", "flag": "🇳🇱" },
    "JPN": { "name": "Japan", "flag": "🇯🇵" },
    "TUN": { "name": "Tunisia", "flag": "🇹🇳" },
    "SWE": { "name": "Sweden", "flag": "🇸🇪" },
    "BEL": { "name": "Belgium", "flag": "🇧🇪" },
    "IRN": { "name": "Iran", "flag": "🇮🇷" },
    "EGY": { "name": "Egypt", "flag": "🇪🇬" },
    "NZL": { "name": "New Zealand", "flag": "🇳🇿" },
    "ESP": { "name": "Spain", "flag": "🇪🇸" },
    "URU": { "name": "Uruguay", "flag": "🇺🇾" },
    "KSA": { "name": "Saudi Arabia", "flag": "🇸🇦" },
    "CPV": { "name": "Cape Verde", "flag": "🇨🇻" },
    "FRA": { "name": "France", "flag": "🇫🇷" },
    "SEN": { "name": "Senegal", "flag": "🇸🇳" },
    "NOR": { "name": "Norway", "flag": "🇳🇴" },
    "IRQ": { "name": "Iraq", "flag": "🇮🇶" },
    "ARG": { "name": "Argentina", "flag": "🇦🇷" },
    "AUT": { "name": "Austria", "flag": "🇦🇹" },
    "ALG": { "name": "Algeria", "flag": "🇩🇿" },
    "JOR": { "name": "Jordan", "flag": "🇯🇴" },
    "POR": { "name": "Portugal", "flag": "🇵🇹" },
    "COL": { "name": "Colombia", "flag": "🇨🇴" },
    "UZB": { "name": "Uzbekistan", "flag": "🇺🇿" },
    "COD": { "name": "DR Congo", "flag": "🇨🇩" },
    "ENG": { "name": "England", "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    "CRO": { "name": "Croatia", "flag": "🇭🇷" },
    "PAN": { "name": "Panama", "flag": "🇵🇦" },
    "GHA": { "name": "Ghana", "flag": "🇬🇭" }
  },
  "groups": {
    "A": ["MEX", "KOR", "RSA", "CZE"],
    "B": ["CAN", "SUI", "QAT", "BIH"],
    "C": ["BRA", "MAR", "SCO", "HAI"],
    "D": ["USA", "PAR", "AUS", "TUR"],
    "E": ["GER", "ECU", "CIV", "CUW"],
    "F": ["NED", "JPN", "TUN", "SWE"],
    "G": ["BEL", "IRN", "EGY", "NZL"],
    "H": ["ESP", "URU", "KSA", "CPV"],
    "I": ["FRA", "SEN", "NOR", "IRQ"],
    "J": ["ARG", "AUT", "ALG", "JOR"],
    "K": ["POR", "COL", "UZB", "COD"],
    "L": ["ENG", "CRO", "PAN", "GHA"]
  },
  "matches": [
    { "g": "A", "md": 1, "date": "2026-06-11", "time": "20:00", "city": "Mexico City", "venue": "Estadio Azteca", "h": "MEX", "a": "RSA", "hs": 2, "as": 0 },
    { "g": "A", "md": 1, "date": "2026-06-11", "time": "16:00", "city": "Guadalajara", "venue": "Estadio Akron", "h": "KOR", "a": "CZE", "hs": 2, "as": 1 },
    { "g": "A", "md": 2, "date": "2026-06-18", "time": "13:00", "city": "Atlanta", "venue": "Mercedes-Benz Stadium", "h": "CZE", "a": "RSA", "hs": null, "as": null },
    { "g": "A", "md": 2, "date": "2026-06-18", "time": "19:00", "city": "Guadalajara", "venue": "Estadio Akron", "h": "MEX", "a": "KOR", "hs": null, "as": null },
    { "g": "A", "md": 3, "date": "2026-06-24", "time": "19:00", "city": "Mexico City", "venue": "Estadio Azteca", "h": "CZE", "a": "MEX", "hs": null, "as": null },
    { "g": "A", "md": 3, "date": "2026-06-24", "time": "19:00", "city": "Monterrey", "venue": "Estadio BBVA", "h": "RSA", "a": "KOR", "hs": null, "as": null },

    { "g": "B", "md": 1, "date": "2026-06-12", "time": "18:00", "city": "Toronto", "venue": "BMO Field", "h": "CAN", "a": "BIH", "hs": 1, "as": 1 },
    { "g": "B", "md": 1, "date": "2026-06-13", "time": "15:00", "city": "San Francisco Bay", "venue": "Levi's Stadium", "h": "QAT", "a": "SUI", "hs": 1, "as": 1 },
    { "g": "B", "md": 2, "date": "2026-06-18", "time": "16:00", "city": "Los Angeles", "venue": "SoFi Stadium", "h": "SUI", "a": "BIH", "hs": null, "as": null },
    { "g": "B", "md": 2, "date": "2026-06-18", "time": "19:00", "city": "Vancouver", "venue": "BC Place", "h": "CAN", "a": "QAT", "hs": null, "as": null },
    { "g": "B", "md": 3, "date": "2026-06-24", "time": "16:00", "city": "Vancouver", "venue": "BC Place", "h": "SUI", "a": "CAN", "hs": null, "as": null },
    { "g": "B", "md": 3, "date": "2026-06-24", "time": "16:00", "city": "Seattle", "venue": "Lumen Field", "h": "BIH", "a": "QAT", "hs": null, "as": null },

    { "g": "C", "md": 1, "date": "2026-06-13", "time": "18:00", "city": "New York / NJ", "venue": "MetLife Stadium", "h": "BRA", "a": "MAR", "hs": 1, "as": 1 },
    { "g": "C", "md": 1, "date": "2026-06-13", "time": "12:00", "city": "Boston", "venue": "Gillette Stadium", "h": "HAI", "a": "SCO", "hs": 0, "as": 1 },
    { "g": "C", "md": 2, "date": "2026-06-19", "time": "12:00", "city": "Boston", "venue": "Gillette Stadium", "h": "SCO", "a": "MAR", "hs": null, "as": null },
    { "g": "C", "md": 2, "date": "2026-06-19", "time": "18:00", "city": "Philadelphia", "venue": "Lincoln Financial Field", "h": "BRA", "a": "HAI", "hs": null, "as": null },
    { "g": "C", "md": 3, "date": "2026-06-24", "time": "15:00", "city": "Miami", "venue": "Hard Rock Stadium", "h": "SCO", "a": "BRA", "hs": null, "as": null },
    { "g": "C", "md": 3, "date": "2026-06-24", "time": "15:00", "city": "Atlanta", "venue": "Mercedes-Benz Stadium", "h": "MAR", "a": "HAI", "hs": null, "as": null },

    { "g": "D", "md": 1, "date": "2026-06-12", "time": "19:00", "city": "Los Angeles", "venue": "SoFi Stadium", "h": "USA", "a": "PAR", "hs": 4, "as": 1 },
    { "g": "D", "md": 1, "date": "2026-06-13", "time": "19:00", "city": "Vancouver", "venue": "BC Place", "h": "AUS", "a": "TUR", "hs": 2, "as": 0 },
    { "g": "D", "md": 2, "date": "2026-06-19", "time": "16:00", "city": "Seattle", "venue": "Lumen Field", "h": "USA", "a": "AUS", "hs": null, "as": null },
    { "g": "D", "md": 2, "date": "2026-06-19", "time": "13:00", "city": "San Francisco Bay", "venue": "Levi's Stadium", "h": "TUR", "a": "PAR", "hs": null, "as": null },
    { "g": "D", "md": 3, "date": "2026-06-25", "time": "16:00", "city": "Los Angeles", "venue": "SoFi Stadium", "h": "TUR", "a": "USA", "hs": null, "as": null },
    { "g": "D", "md": 3, "date": "2026-06-25", "time": "16:00", "city": "San Francisco Bay", "venue": "Levi's Stadium", "h": "PAR", "a": "AUS", "hs": null, "as": null },

    { "g": "E", "md": 1, "date": "2026-06-14", "time": "15:00", "city": "Houston", "venue": "NRG Stadium", "h": "GER", "a": "CUW", "hs": 7, "as": 1 },
    { "g": "E", "md": 1, "date": "2026-06-14", "time": "18:00", "city": "Philadelphia", "venue": "Lincoln Financial Field", "h": "CIV", "a": "ECU", "hs": 1, "as": 0 },
    { "g": "E", "md": 2, "date": "2026-06-20", "time": "18:00", "city": "Toronto", "venue": "BMO Field", "h": "GER", "a": "CIV", "hs": null, "as": null },
    { "g": "E", "md": 2, "date": "2026-06-20", "time": "15:00", "city": "Kansas City", "venue": "Arrowhead Stadium", "h": "ECU", "a": "CUW", "hs": null, "as": null },
    { "g": "E", "md": 3, "date": "2026-06-25", "time": "13:00", "city": "Philadelphia", "venue": "Lincoln Financial Field", "h": "CUW", "a": "CIV", "hs": null, "as": null },
    { "g": "E", "md": 3, "date": "2026-06-25", "time": "13:00", "city": "New York / NJ", "venue": "MetLife Stadium", "h": "ECU", "a": "GER", "hs": null, "as": null },

    { "g": "F", "md": 1, "date": "2026-06-14", "time": "13:00", "city": "Dallas", "venue": "AT&T Stadium", "h": "NED", "a": "JPN", "hs": 2, "as": 2 },
    { "g": "F", "md": 1, "date": "2026-06-14", "time": "21:00", "city": "Monterrey", "venue": "Estadio BBVA", "h": "SWE", "a": "TUN", "hs": 5, "as": 1 },
    { "g": "F", "md": 2, "date": "2026-06-20", "time": "12:00", "city": "Houston", "venue": "NRG Stadium", "h": "NED", "a": "SWE", "hs": null, "as": null },
    { "g": "F", "md": 2, "date": "2026-06-20", "time": "21:00", "city": "Monterrey", "venue": "Estadio BBVA", "h": "TUN", "a": "JPN", "hs": null, "as": null },
    { "g": "F", "md": 3, "date": "2026-06-25", "time": "19:00", "city": "Dallas", "venue": "AT&T Stadium", "h": "JPN", "a": "SWE", "hs": null, "as": null },
    { "g": "F", "md": 3, "date": "2026-06-25", "time": "19:00", "city": "Kansas City", "venue": "Arrowhead Stadium", "h": "TUN", "a": "NED", "hs": null, "as": null },

    { "g": "G", "md": 1, "date": "2026-06-15", "time": "12:00", "city": "Seattle", "venue": "Lumen Field", "h": "BEL", "a": "EGY", "hs": null, "as": null },
    { "g": "G", "md": 1, "date": "2026-06-15", "time": "18:00", "city": "Los Angeles", "venue": "SoFi Stadium", "h": "IRN", "a": "NZL", "hs": null, "as": null },
    { "g": "G", "md": 2, "date": "2026-06-21", "time": "12:00", "city": "Los Angeles", "venue": "SoFi Stadium", "h": "BEL", "a": "IRN", "hs": null, "as": null },
    { "g": "G", "md": 2, "date": "2026-06-21", "time": "18:00", "city": "Vancouver", "venue": "BC Place", "h": "NZL", "a": "EGY", "hs": null, "as": null },
    { "g": "G", "md": 3, "date": "2026-06-26", "time": "20:00", "city": "Seattle", "venue": "Lumen Field", "h": "EGY", "a": "IRN", "hs": null, "as": null },
    { "g": "G", "md": 3, "date": "2026-06-26", "time": "20:00", "city": "Vancouver", "venue": "BC Place", "h": "NZL", "a": "BEL", "hs": null, "as": null },

    { "g": "H", "md": 1, "date": "2026-06-15", "time": "15:00", "city": "Atlanta", "venue": "Mercedes-Benz Stadium", "h": "ESP", "a": "CPV", "hs": 0, "as": 0 },
    { "g": "H", "md": 1, "date": "2026-06-15", "time": "21:00", "city": "Miami", "venue": "Hard Rock Stadium", "h": "KSA", "a": "URU", "hs": null, "as": null },
    { "g": "H", "md": 2, "date": "2026-06-21", "time": "15:00", "city": "Atlanta", "venue": "Mercedes-Benz Stadium", "h": "ESP", "a": "KSA", "hs": null, "as": null },
    { "g": "H", "md": 2, "date": "2026-06-21", "time": "21:00", "city": "Miami", "venue": "Hard Rock Stadium", "h": "URU", "a": "CPV", "hs": null, "as": null },
    { "g": "H", "md": 3, "date": "2026-06-26", "time": "15:00", "city": "Houston", "venue": "NRG Stadium", "h": "CPV", "a": "KSA", "hs": null, "as": null },
    { "g": "H", "md": 3, "date": "2026-06-26", "time": "15:00", "city": "Guadalajara", "venue": "Estadio Akron", "h": "URU", "a": "ESP", "hs": null, "as": null },

    { "g": "I", "md": 1, "date": "2026-06-16", "time": "18:00", "city": "New York / NJ", "venue": "MetLife Stadium", "h": "FRA", "a": "SEN", "hs": null, "as": null },
    { "g": "I", "md": 1, "date": "2026-06-16", "time": "12:00", "city": "Boston", "venue": "Gillette Stadium", "h": "IRQ", "a": "NOR", "hs": null, "as": null },
    { "g": "I", "md": 2, "date": "2026-06-22", "time": "12:00", "city": "Philadelphia", "venue": "Lincoln Financial Field", "h": "FRA", "a": "IRQ", "hs": null, "as": null },
    { "g": "I", "md": 2, "date": "2026-06-22", "time": "18:00", "city": "New York / NJ", "venue": "MetLife Stadium", "h": "NOR", "a": "SEN", "hs": null, "as": null },
    { "g": "I", "md": 3, "date": "2026-06-26", "time": "12:00", "city": "Boston", "venue": "Gillette Stadium", "h": "NOR", "a": "FRA", "hs": null, "as": null },
    { "g": "I", "md": 3, "date": "2026-06-26", "time": "12:00", "city": "Toronto", "venue": "BMO Field", "h": "SEN", "a": "IRQ", "hs": null, "as": null },

    { "g": "J", "md": 1, "date": "2026-06-16", "time": "15:00", "city": "Kansas City", "venue": "Arrowhead Stadium", "h": "ARG", "a": "ALG", "hs": null, "as": null },
    { "g": "J", "md": 1, "date": "2026-06-16", "time": "21:00", "city": "San Francisco Bay", "venue": "Levi's Stadium", "h": "AUT", "a": "JOR", "hs": null, "as": null },
    { "g": "J", "md": 2, "date": "2026-06-22", "time": "15:00", "city": "Dallas", "venue": "AT&T Stadium", "h": "ARG", "a": "AUT", "hs": null, "as": null },
    { "g": "J", "md": 2, "date": "2026-06-22", "time": "21:00", "city": "San Francisco Bay", "venue": "Levi's Stadium", "h": "JOR", "a": "ALG", "hs": null, "as": null },
    { "g": "J", "md": 3, "date": "2026-06-27", "time": "15:00", "city": "Kansas City", "venue": "Arrowhead Stadium", "h": "ALG", "a": "AUT", "hs": null, "as": null },
    { "g": "J", "md": 3, "date": "2026-06-27", "time": "15:00", "city": "Dallas", "venue": "AT&T Stadium", "h": "JOR", "a": "ARG", "hs": null, "as": null },

    { "g": "K", "md": 1, "date": "2026-06-17", "time": "15:00", "city": "Houston", "venue": "NRG Stadium", "h": "POR", "a": "COD", "hs": null, "as": null },
    { "g": "K", "md": 1, "date": "2026-06-17", "time": "19:00", "city": "Mexico City", "venue": "Estadio Azteca", "h": "UZB", "a": "COL", "hs": null, "as": null },
    { "g": "K", "md": 2, "date": "2026-06-23", "time": "15:00", "city": "Houston", "venue": "NRG Stadium", "h": "POR", "a": "UZB", "hs": null, "as": null },
    { "g": "K", "md": 2, "date": "2026-06-23", "time": "19:00", "city": "Guadalajara", "venue": "Estadio Akron", "h": "COL", "a": "COD", "hs": null, "as": null },
    { "g": "K", "md": 3, "date": "2026-06-27", "time": "19:00", "city": "Miami", "venue": "Hard Rock Stadium", "h": "COL", "a": "POR", "hs": null, "as": null },
    { "g": "K", "md": 3, "date": "2026-06-27", "time": "19:00", "city": "Atlanta", "venue": "Mercedes-Benz Stadium", "h": "COD", "a": "UZB", "hs": null, "as": null },

    { "g": "L", "md": 1, "date": "2026-06-17", "time": "16:00", "city": "Dallas", "venue": "AT&T Stadium", "h": "ENG", "a": "CRO", "hs": null, "as": null },
    { "g": "L", "md": 1, "date": "2026-06-17", "time": "12:00", "city": "Toronto", "venue": "BMO Field", "h": "GHA", "a": "PAN", "hs": null, "as": null },
    { "g": "L", "md": 2, "date": "2026-06-23", "time": "12:00", "city": "Boston", "venue": "Gillette Stadium", "h": "ENG", "a": "GHA", "hs": null, "as": null },
    { "g": "L", "md": 2, "date": "2026-06-23", "time": "16:00", "city": "Toronto", "venue": "BMO Field", "h": "PAN", "a": "CRO", "hs": null, "as": null },
    { "g": "L", "md": 3, "date": "2026-06-27", "time": "12:00", "city": "New York / NJ", "venue": "MetLife Stadium", "h": "PAN", "a": "ENG", "hs": null, "as": null },
    { "g": "L", "md": 3, "date": "2026-06-27", "time": "12:00", "city": "Philadelphia", "venue": "Lincoln Financial Field", "h": "CRO", "a": "GHA", "hs": null, "as": null }
  ],
  "knockout": [
    { "round": "Round of 32", "dates": "Jun 28 – Jul 3", "count": 16 },
    { "round": "Round of 16", "dates": "Jul 4 – Jul 7", "count": 8 },
    { "round": "Quarter-finals", "dates": "Jul 9 – Jul 11", "count": 4 },
    { "round": "Semi-finals", "dates": "Jul 14 – Jul 15", "count": 2 },
    { "round": "Third place", "dates": "Jul 18", "count": 1 },
    { "round": "Final", "dates": "Jul 19", "count": 1 }
  ]
}
;
