import { chromium } from 'playwright-core';
import { setTimeout as sleep } from 'node:timers/promises';
const b = await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--no-sandbox','--disable-background-networking','--no-first-run','--allow-file-access-from-files']});
const p = await b.newPage({viewport:{width:1400,height:820}});
const errs=[]; p.on('pageerror',e=>errs.push('PAGEERROR: '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('CONSOLE: '+m.text())});
await p.goto('file:///home/user/Test/lysbrud/dist/lysbrud.html');
await sleep(1800);
await p.click('#spin-button');
await sleep(6000);
const st = await p.evaluate(()=>({bal:document.getElementById('balance-value').textContent, win:document.getElementById('win-value').textContent, board:!!window.LYSBRUD.view.board}));
console.log('enkeltfil fra disk:', JSON.stringify(st));
await p.screenshot({path:'/tmp/shots/dist.png'});
console.log(errs.length?errs.slice(0,6).join('\n'):'NO ERRORS');
await b.close();
