// Mathematics materials library (SPEC §11): SVG components in the animals' style that all task
// kinds and scenes are built from. See design.html#materials for every item in every state.
export { Coin, Banknote, COIN_VALUES, NOTE_VALUES, COIN_MM, NOTE_MM, coinWidth, noteWidth } from './Money'
export type { CoinOre, NoteKr } from './Money'
export { AnalogClock, DigitalClock, handAngles, digitalText } from './Clock'
export { Ruler, RULER } from './Ruler'
export { Base10Block, Base10Group } from './Base10'
export type { Base10Kind } from './Base10'
export { TenFrame, DoubleTenFrame, Die, Hand, Fingers, BeadString } from './Counting'
export type { SkinTone } from './Counting'
export { Thing, ThingArt, THING_IDS } from './Things'
export type { KnownThing } from './Things'
export { Shape2D, SHAPE_IDS, SHAPE_VARIANTS } from './Shapes'
export { Solid3D, SOLID_IDS } from './Solids'
export { Seesaw, PanScale } from './Balance'
export { BarChart, Pictogram } from './Charts'
export type { ChartDatum, RenderCat } from './Charts'
export { FractionShape, FractionBars } from './Fractions'
export { CoordGrid, SquareGrid, HundredBoard } from './Grids'
export type { GridPoint } from './Grids'
export { NumberLine, NL, xOf, niceStep } from './NumberLine'
export { MAT, INK, MINUTE_HAND } from './palette'
export type { Tone, ToneName } from './palette'
