// Parent-facing names for the families that content/skills.ts lists by id only (the dashboard's
// "opdeling pr. familie"). A label in the skill table wins; these fill the gaps. Proposed for
// content/skills.ts (FamilyDef.label), where they belong.
import { SKILL_BY_ID } from '../content/skills'
import type { SkillId } from '../engine/types'

const table = (n: number) => `${n}-tabellen`
const div = (n: number) => `Division med ${n}`

const LABELS: Readonly<Record<string, string>> = {
  'hear100/d2x': 'Tyverne (20–29)', 'hear100/d3x': 'Trediverne (30–39)', 'hear100/d4x': 'Fyrrerne (40–49)',
  'hear100/d5x': 'Halvtredserne (50–59)', 'hear100/d6x': 'Tresserne (60–69)', 'hear100/d7x': 'Halvfjerdserne (70–79)',
  'hear100/d8x': 'Firserne (80–89)', 'hear100/d9x': 'Halvfemserne (90–99)',
  'order100/plus1': 'Én mere', 'order100/minus1': 'Én mindre', 'order100/plus10': 'Ti mere', 'order100/minus10': 'Ti mindre',
  'order100/crossTen': 'Over tieren', 'order100/biggerDiffTens': 'Størst, forskellige tiere',
  'order100/biggerSwapped': 'Størst, ombyttede cifre (fx 46 og 64)',
  'numberLine100/placeTens': 'Placér hele tiere', 'numberLine100/placeAny': 'Placér et tal', 'numberLine100/readArrow': 'Aflæs pilen',
  'hear1000/hundreds': 'Hele hundreder', 'hear1000/h0o': 'Hundreder og enere (fx 304)', 'hear1000/hTeen': 'Hundreder og 11–19 (fx 517)',
  'hear1000/hT0': 'Hundreder og hele tiere (fx 640)', 'hear1000/hTO': 'Hundreder, tiere og enere',
  'order1000/plus1': 'Én mere', 'order1000/plus10': 'Ti mere', 'order1000/plus100': 'Hundrede mere', 'order1000/minus1': 'Én mindre',
  'order1000/minus10': 'Ti mindre', 'order1000/minus100': 'Hundrede mindre', 'order1000/crossHundred': 'Over hundredet',
  'order1000/bigger3': 'Størst af tre', 'order1000/biggerMixed': 'Størst, blandede tal',
  'numberLine1000/placeHundreds': 'Placér hele hundreder', 'numberLine1000/placeAny': 'Placér et tal',
  'numberLine1000/round10': 'Afrund til tiere', 'numberLine1000/round100': 'Afrund til hundreder',
  'tensOnes/build': 'Byg tallet', 'tensOnes/decompose': 'Del tallet i tiere og enere',
  'tensOnes/swapped': 'Tiere og enere i blandet rækkefølge', 'tensOnes/expand': 'Skriv som tiere + enere',
  'placeValue1000/buildHTO': 'Byg tallet', 'placeValue1000/zeroPlace': 'Nul som pladsholder',
  'placeValue1000/digitValue': 'Hvad cifret er værd', 'placeValue1000/expand': 'Skriv som hundreder + tiere + enere',
  'placeValue1000/regroup': 'Veksling (fx 12 tiere)',
  'tenFriends/pairs': 'Tiervenner',
  'doubles/to5': 'Dobbelt op til 5 + 5', 'doubles/to10': 'Dobbelt op til 10 + 10',
  'halves/to10': 'Halvdelen af tal op til 10', 'halves/to20': 'Halvdelen af tal op til 20',
  'addSub20Simple/addTeen': 'Plus mellem 11 og 19 (fx 13 + 4)', 'addSub20Simple/subTeen': 'Minus mellem 11 og 19 (fx 17 − 5)',
  'addSub20Simple/tenPlus': 'Ti plus et tal (fx 10 + 6)',
  'addTo20/bridge10': 'Plus over tieren', 'subTo20/bridge10': 'Minus over tieren',
  'tens100/addTens': 'Plus med hele tiere', 'tens100/subTens': 'Minus med hele tiere',
  'add100NoCarry/TOplusO': 'Tocifret + enere (fx 34 + 5)', 'add100NoCarry/TOplusT0': 'Tocifret + hele tiere (fx 34 + 20)',
  'add100NoCarry/TOplusTO': 'Tocifret + tocifret (fx 34 + 25)',
  'sub100NoBorrow/TOminusO': 'Tocifret − enere (fx 38 − 5)', 'sub100NoBorrow/TOminusT0': 'Tocifret − hele tiere (fx 58 − 20)',
  'sub100NoBorrow/TOminusTO': 'Tocifret − tocifret (fx 58 − 23)',
  'add100Carry/toNextTen': 'Op til næste tier (fx 37 + 3)', 'add100Carry/TOplusOcarry': 'Enere over tieren (fx 38 + 5)',
  'add100Carry/TOplusTOcarry': 'Tocifret over tieren (fx 38 + 45)', 'add100Carry/nearTen': 'Plus tæt på en tier (fx 46 + 19)',
  'add100Carry/TOplusTOover100': 'Over 100 (fx 78 + 45)',
  'sub100Borrow/fromTen': 'Fra en hel tier (fx 40 − 7)', 'sub100Borrow/TOminusOborrow': 'Enere med veksling (fx 43 − 7)',
  'sub100Borrow/TOminusTOborrow': 'Tocifret med veksling (fx 53 − 27)', 'sub100Borrow/nearTen': 'Minus tæt på en tier (fx 64 − 19)',
  'addSub1000Round/HplusH': 'Hundreder plus hundreder', 'addSub1000Round/HminusH': 'Hundreder minus hundreder',
  'addSub1000Round/HTplusT': 'Plus hele tiere (fx 340 + 20)', 'addSub1000Round/HTminusT': 'Minus hele tiere (fx 340 − 20)',
  'addSub1000Round/HplusTO': 'Hundreder plus tocifret (fx 300 + 45)', 'addSub1000Round/HTplusTcarry': 'Tiere over hundredet (fx 280 + 40)',
  'add1000/HTOplusOcarry': 'Trecifret + enere over tieren', 'add1000/HTOplusTO': 'Trecifret + tocifret',
  'add1000/HTOplusTOcarry1': 'Trecifret + tocifret over tieren', 'add1000/HTOplusTOcarry10': 'Trecifret + tocifret over hundredet',
  'add1000/HTOplusHTO': 'Trecifret + trecifret', 'add1000/HTOplusHTOcarry': 'Trecifret + trecifret med mente',
  'sub1000/HTOminusOborrow': 'Trecifret − enere med veksling', 'sub1000/HTOminusTO': 'Trecifret − tocifret',
  'sub1000/HTOminusTOborrow': 'Trecifret − tocifret med veksling', 'sub1000/HTOminusHTO': 'Trecifret − trecifret',
  'sub1000/HTOminusHTOborrow': 'Trecifret − trecifret med veksling', 'sub1000/acrossZero': 'Veksling over nul (fx 403 − 158)',
  'groupsOf/groups': 'Grupper af lige mange', 'shareEqually/share': 'Del ligeligt',
  'mul2510/t2': table(2), 'mul2510/t5': table(5), 'mul2510/t10': table(10), 'mul34/t3': table(3), 'mul34/t4': table(4),
  'mul6to9/t6': table(6), 'mul6to9/t7': table(7), 'mul6to9/t8': table(8), 'mul6to9/t9': table(9),
  'div2510/d2': div(2), 'div2510/d5': div(5), 'div2510/d10': div(10), 'divAll/d3': div(3), 'divAll/d4': div(4),
  'divAll/d6': div(6), 'divAll/d7': div(7), 'divAll/d8': div(8), 'divAll/d9': div(9),
  'mulTens/oneDigitTimesTens': 'Etcifret · hele tiere (fx 3 · 40)', 'mulTens/tensTimesOneDigit': 'Hele tiere · etcifret (fx 40 · 3)',
  'patterns/AB': 'AB-mønstre', 'patterns/AAB': 'AAB-mønstre', 'patterns/ABB': 'ABB-mønstre', 'patterns/ABC': 'ABC-mønstre',
  'patterns/growing': 'Voksende mønstre',
  'missingPart10/missing': 'Det manglende tal',
  'skipCount/step2': 'Spring på 2', 'skipCount/step5': 'Spring på 5', 'skipCount/step10': 'Spring på 10',
  'skipCount/step10offset': 'Spring på 10 fra et skævt tal (fx 3, 13, 23)', 'skipCount/back10': 'Baglæns i spring på 10',
  'skipCount/step100': 'Spring på 100', 'skipCount/step25': 'Spring på 25',
  'missingPart100/addendCross20': 'Det manglende tal over 20', 'missingPart100/toHundred': 'Op til 100 (fx 37 + ? = 100)',
  'missingPart100/subtrahend': 'Hvor meget blev trukket fra?', 'missingPart100/minuend': 'Hvad startede vi med?',
  'inverseOps/addToSub': 'Fra plus til minus', 'inverseOps/subToAdd': 'Fra minus til plus', 'inverseOps/mulToDiv': 'Fra gange til division',
  'equalSides/trueFalse': 'Passer lighedstegnet?', 'equalSides/balanceAdd': 'Vægten i balance med plus',
  'equalSides/balanceSub': 'Vægten i balance med minus', 'equalSides/balanceMixed': 'Vægten i balance, blandet',
  'shapes2D/basic': 'Cirkel, trekant og firkant', 'shapes2D/squareRect': 'Kvadrat og rektangel',
  'shapes2D/polygons': 'Femkant, sekskant og ottekant',
  'sidesCorners/sides': 'Sider', 'sidesCorners/corners': 'Hjørner',
  'shapes3D/names': 'Navne på rumlige figurer', 'shapes3D/props': 'Flader, kanter og hjørner',
  'sortShapes/threeCorners': 'Tre hjørner', 'sortShapes/fourCorners': 'Fire hjørner', 'sortShapes/noCorners': 'Ingen hjørner',
  'sortShapes/fourEqualSides': 'Fire lige lange sider', 'sortShapes/rightAngle': 'Rette vinkler',
  'symmetry/isSymLine': 'Er det en symmetriakse?', 'symmetry/mirrorGrid': 'Spejl i et net',
  'composeShapes/compose': 'Sammensæt figurer',
  'area/countSquares': 'Tæl felter', 'area/rowsCols': 'Rækker gange søjler', 'area/lShape': 'L-formede figurer',
  'area/compareArea': 'Sammenlign arealer',
  'gridCoords/readPoint': 'Aflæs et punkt', 'gridCoords/placePoint': 'Sæt et punkt',
  'clockHour/hour': 'Hele timer', 'clockHalf/half': 'Halve timer',
  'clockQuarter/quarterPast': 'Kvart over', 'clockQuarter/quarterTo': 'Kvart i',
  'clockFive/over': 'Minutter over', 'clockFive/iHalv': 'Minutter i halv', 'clockFive/overHalv': 'Minutter over halv',
  'clockFive/i': 'Minutter i', 'clockFive/halfForm': 'Tider sagt med »halv«',
  'clockDigital/analogToDigital': 'Fra viserur til digitalt ur', 'clockDigital/digital24': 'Døgnets 24 timer',
  'clockElapsed/plusHour': 'En time senere', 'clockElapsed/plusHalf': 'En halv time senere',
  'clockElapsed/plusQuarter': 'Et kvarter senere', 'clockElapsed/minusHalf': 'En halv time før',
  'coinNames/coins': 'Mønter', 'coinNames/notes': 'Sedler',
  'countCoins/sameCoins': 'Ens mønter', 'countCoins/mixedTo20': 'Blandede mønter op til 20 kr.',
  'countCoins/mixedTo100': 'Blandede mønter op til 100 kr.', 'countCoins/biggestFirst': 'Tæl de største først',
  'payExact/to20': 'Betal op til 20 kr.', 'payExact/to50': 'Betal op til 50 kr.', 'payExact/to100': 'Betal op til 100 kr.',
  'payExact/fewestCoins': 'Betal med færrest mønter',
  'change/from10': 'Byttepenge fra 10 kr.', 'change/from20': 'Byttepenge fra 20 kr.', 'change/from50': 'Byttepenge fra 50 kr.',
  'change/from100': 'Byttepenge fra 100 kr.',
  'kronerOre/readAmount': 'Aflæs beløb med øre', 'kronerOre/fiftiesInKroner': 'Halvtredsører og kroner',
  'kronerOre/addHalves': 'Læg halve kroner sammen',
  'compareLength/aligned': 'Ting på linje', 'compareLength/offset': 'Forskudte ting',
  'weightCompare/congruent': 'Den største er tungest', 'weightCompare/conflict': 'Den største er ikke tungest',
  'measureUnits/cubes': 'Mål med klodser', 'measureUnits/clips': 'Mål med clips',
  'rulerRead/from0': 'Fra 0', 'rulerRead/offset': 'Fra et andet tal end 0',
  'unitChoice/length': 'Længde', 'unitChoice/weight': 'Vægt',
  'readChart/readPicto': 'Aflæs et billeddiagram', 'readChart/readBar': 'Aflæs et søjlediagram',
  'readChart/mostLeast': 'Flest og færrest', 'readChart/difference': 'Hvor mange flere?',
  'convertCmM/mToCm': 'Meter til centimeter', 'convertCmM/mCmToCm': 'Meter og centimeter til centimeter',
  'convertCmM/cmToMCm': 'Centimeter til meter og centimeter', 'convertCmM/compareMixed': 'Sammenlign længder',
  'halfShape/equal': 'Lige store dele', 'halfShape/unequal': 'Skæve dele',
  'fractionShape/basic': 'Halve, tredjedele og fjerdedele', 'fractionShape/nonUnit': 'Fx 3/4 og 2/3',
  'fractionOfSet/halfOf': 'Halvdelen af', 'fractionOfSet/quarterOf': 'En fjerdedel af', 'fractionOfSet/thirdOf': 'En tredjedel af',
  'fractionOfSet/threeQuartersOf': 'Tre fjerdedele af',
  'fractionCompare/pairBigger': 'Hvilken er størst?', 'fractionCompare/pairSmaller': 'Hvilken er mindst?',
  'fractionCompare/order4': 'Sæt fire brøker i rækkefølge',
}

/** A family's parent-facing name: the skill table's label, else ours, else "Del N". */
export function familyLabel(skill: SkillId, family: string): string {
  const meta = SKILL_BY_ID[skill]
  const def = meta?.families.find((f) => f.id === family)
  if (def && def.label !== def.id) return def.label
  return LABELS[`${skill}/${family}`] ?? (def ? `Del ${def.rank + 1}` : family)
}

/** Every family label we hold (tests check they cover the table). */
export const FAMILY_LABEL_KEYS: readonly string[] = Object.keys(LABELS)
