// Writes src/math/config.generated.ts (tuned constants + REPORT + model hash).
import { createHash } from 'node:crypto';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { MathConfig, MathReport } from '../src/math/config.ts';
import { stableStringify } from '../src/math/hash.ts';

export const GENERATED_PATH = fileURLToPath(new URL('../src/math/config.generated.ts', import.meta.url));

/** SHA-256 (node:crypto) of the canonical JSON of the config without its modelHash field. */
export function modelHashOf(cfg: MathConfig): string {
  const { modelHash: _drop, ...rest } = cfg;
  void _drop;
  return createHash('sha256').update(stableStringify(rest)).digest('hex');
}

const num = (x: number) => (Number.isInteger(x) ? String(x) : String(+x.toPrecision(12)));
const arr = (a: number[]) => '[' + a.map(num).join(', ') + ']';

function objLit(o: Record<string, unknown>, indent: string): string {
  const lines: string[] = [];
  for (const [k, v] of Object.entries(o)) {
    let s: string;
    if (typeof v === 'number') s = num(v);
    else if (typeof v === 'string') s = JSON.stringify(v);
    else if (Array.isArray(v) && v.length && Array.isArray(v[0])) s = '[\n' + (v as number[][]).map((r) => indent + '  ' + arr(r) + ',').join('\n') + '\n' + indent + ']';
    else if (Array.isArray(v) && v.every((x) => typeof x === 'number')) s = arr(v as number[]);
    else s = JSON.stringify(v);
    lines.push(`${indent}${k}: ${s},`);
  }
  return lines.join('\n');
}

export function writeGenerated(cfg: MathConfig, report: MathReport, note: string): void {
  const src = `// AUTO-GENERATED by ${note} — do not edit by hand. Re-run \`node sim/tune.ts\` then \`node sim/run.ts\`.
// modelHash = SHA-256 (node:crypto) of the canonical JSON of GENERATED_CONFIG without modelHash.
import type { MathConfig, MathReport } from './config.ts';

export const GENERATED_CONFIG: MathConfig = {
${objLit(cfg as unknown as Record<string, unknown>, '  ')}
};

export const GENERATED_REPORT: MathReport = {
${objLit(report as unknown as Record<string, unknown>, '  ')}
};
`;
  writeFileSync(GENERATED_PATH, src);
}

export function readGeneratedText(): string {
  return existsSync(GENERATED_PATH) ? readFileSync(GENERATED_PATH, 'utf8') : '';
}
